export const CHANGE_NEW_BOOK = 'CHANGE_NEW_BOOK';
export const ADD_NEW_BOOK = 'ADD_NEW_BOOK';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_BOOK_PROPERTY = 'CHANGE_BOOK_PROPERTY';
export const DELETE_BOOK = 'DELETE_BOOK';
