export const CHANGE_NEW_ITEM = 'CHANGE_NEW_ITEM';
export const ADD_NEW_ITEM = 'ADD_NEW_ITEM';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_ITEM_PROPERTY = 'CHANGE_ITEM_PROPERTY';
export const DELETE_ITEM = 'DELETE_ITEM';
